#!/bin/bash

# Fail early if there's an issue
set -e

# Tree to see the working directory's contents
#find . -type d -print | sed -e 's;[^/]*/;|____;g;s;____|;  |;g'
find . | sort | sed -e 's;[^/]*/;  |;g;s;|; ├──;'

# When .cache files are created, they need to know where HOME is to write there.
# In this case, that should be the HTCondor scratch dir the job is executing in.
export HOME=$(pwd)

# HTCondor vanilla-universe jobs start with a near-empty environment: PATH is
# not exported (bash falls back to a compiled-in default to find commands, but
# Python's os.environ has no PATH key, which crashes Snakemake's scheduler with
# `KeyError: 'PATH'`).  Guarantee a sane PATH so the EP-side snakemake — and the
# tools it shells out to — are found.  (The upstream torture test uses
# universe="container", where the image supplies PATH; this CI copy runs vanilla.)
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH}"

# However this wrapper is set up, the EP will be handed a list of Snakemake arguments
# that were generated by Snakemake at the AP. Those define exactly which step/rule to run
# and with which parameters. Those args must be passed back to Snakemake here to run
# that step.
snakemake "$@"
